nginx:
  build: ./nginx
  restart: always
  links:
    - haproxy
  ports:
    - '80:80'
# https://github.com/vegasbrianc/docker-compose-demo/blob/master/docker-compose.yml
haproxy:
  image: tutum/haproxy
  links:
   - web
  environment:
   - BACKEND_PORT=8000
web:
  build: .
  env_file: .env
  restart: always
