apiVersion: v1
kind: Service
metadata:
  name: jsonp
  labels:
    run: jsonp
spec:
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: jsonp
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jsonp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jsonp
    spec:
      containers:
      - name: web
        image: afeld/jsonp
        ports:
        - containerPort: 8000
