service: jsonp

provider:
  name: aws
  runtime: nodejs6.10
  # only deploy production, because of https://github.com/amplify-education/serverless-domain-manager/issues/60
  stage: prod

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
