apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jsonp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jsonp
    spec:
      containers:
      - name: web
        image: afeld/jsonp
        ports:
        - containerPort: 8000
