apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jsonp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jsonp
    spec:
      containers:
      - name: web
        image: afeld/jsonp
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic
              key: license-key
